routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

$this->get('admin-panel/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin-panel/login', 'Auth\LoginController@login');
//$this->post('admin-panel/logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
//$this->get('admin-panel/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');


Route::group(['middleware'=>'auth'],function (){

    Route::resource('admin-panel/users', 'AdminPanel\UserController');

    Route::resource('admin-panel/roles', 'AdminPanel\RoleController');

    Route::resource('admin-panel/products', 'AdminPanel\ProductController');

    Route::resource('admin-panel/images', 'AdminPanel\ImageController');

    Route::resource('admin-panel/shipments', 'AdminPanel\ShipmentController');

    Route::resource('admin-panel/postmen', 'AdminPanel\PostmanController');

    Route::resource('admin-panel/transactions', 'AdminPanel\TransactionController');

    Route::resource('admin-panel/allsells', 'AdminPanel\AllsellController');

    Route::resource('admin-panel/comments', 'AdminPanel\CommentController');

    Route::resource('admin-panel/images', 'AdminPanel\ImageController');

    Route::resource('admin-panel/shipmentTypes', 'AdminPanel\ShipmentTypeController');

    Route::resource('admin-panel/paymentTypes', 'AdminPanel\PaymentTypeController');

    Route::resource('admin-panel/productTypes', 'AdminPanel\ProductTypeController');

    Route::resource('admin-panel/posts', 'AdminPanel\PostController');

    Route::get('/admin-panel', 'AdminPanel\AdminPanelController@index');

});

//Route::get('/home', 'HomeController@index');

//API

Route::get('/buyershow/{id}','Front\API\BuyerProductController@show');
Route::get('/buyershowall', 'Front\API\BuyerProductController@showall');
Route::get('/comm/{id}', 'Front\api\BuyerProductController@showcomments');
Route::get('/clientshowpost/{id}', 'Front\API\ClientPostController@show');
Route::get('/clientshowallpost', 'Front\API\ClientPostController@showall');

Route::get('/cartdtail', 'Front\API\CartDtailController@showall');


Route::get('login', 'Front\LoginController@index');

//Route::get('register', 'Front\RegisterController@index');

Route::get('/', 'Front\HomeController@index');

Route::get('address', 'Front\AddressController@index');

Route::get('reviewaddress', 'Front\ReviewAddressController@index');

Route::get('calculations', 'Front\CalculationsController@index');

Route::get('cart', 'Front\Cart1Controller@index');

Route::get('review', 'Front\ReviewController@index');

Route::get('paymentsuccess', 'Front\PayMentSuccessController@index');

Route::get('product', 'Front\ProductController@index');

Route::get('product/{id}', 'Front\ProductController@index');

Route::get('profile', 'Front\ProfileController@index');

Route::get('blog', 'Front\BlogController@index');

//Route::get('blog/post', 'Front\PostController@index');
Route::get('blog/post/{id}', 'Front\PostController@show');

Route::get('finalstep', 'Front\FinalStepController@index');

//summernote store route
Route::post('/summernote','SummernoteController@store')->name('summernotePersist');

//summernote display route
Route::get('/summernote_display','SummernoteController@show')->name('summernoteDispay');

Route::resource('posts', 'PostController');

Route::resource('postTags', 'PostTagController');





//
Route::get('/profile/profile',function(){
    return view('front.Profile.profile');
});
Route::get('/profile/information',function(){
    return view('front.Profile.information');
});
Route::get('/profile/address',function(){
    return view('front.Profile.address');
});
Route::get('/profile/bookmark',function(){
    return view('front.Profile.bookmark');
});
Route::get('/profile/changeAvatar',function(){
    return view('front.Profile.changeAvatar');
});
Route::get('/profile/changePassword',function(){
    return view('front.Profile.changePassword');
});
Route::get('/profile/order',function(){
    return view('front.Profile.order');
});
Route::get('/profile/question',function(){
    return view('front.Profile.question');
});
Route::get('/profile/requestreturn',function(){
    return view('front.Profile.requestreturn');
});

app/Http/Controllers/AdminPanel/TransactionController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Http\Requests\CreateTransactionRequest;
use App\Http\Requests\UpdateTransactionRequest;
use App\Repositories\TransactionRepository;
use App\Repositories\AllsellRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Http\Controllers\AdminPanel\CheckRoleAdmin;

class TransactionController extends AppBaseController
{
    /** @var  TransactionRepository */
    private $transactionRepository;
//    private $allsellrepository;

    public function __construct(TransactionRepository $transactionRepo,AllsellRepository $allsellrepository)
    {
        $this->transactionRepository = $transactionRepo;
//        $this->allsellrepository = $allsellrepository;
    }

    /**
     * Display a listing of the Transaction.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $this->transactionRepository->pushCriteria(new RequestCriteria($request));
        $transactions = $this->transactionRepository->all();

        return view('transactions.index')
            ->with('transactions', $transactions);
    }

    /**
     * Show the form for creating a new Transaction.
     *
     * @return Response
     */
    public function create()
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        return view('transactions.create');
    }

    /**
     * Store a newly created Transaction in storage.
     *
     * @param CreateTransactionRequest $request
     *
     * @return Response
     */
    public function store(CreateTransactionRequest $request)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $input = $request->all();

        $transaction = $this->transactionRepository->create($input);

        Flash::success('Transaction saved successfully.');

        return redirect(route('transactions.index'));
    }

    /**
     * Display the specified Transaction.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $transaction = $this->transactionRepository->findWithoutFail($id);

        if (empty($transaction)) {
            Flash::error('Transaction not found');

            return redirect(route('transactions.index'));
        }

        return view('transactions.show')
            ->with('transaction', $transaction)
            ->with('allsells',$transaction->allsells)
            ->with('shipments',$transaction->shipments);
    }

    /**
     * Show the form for editing the specified Transaction.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $transaction = $this->transactionRepository->findWithoutFail($id);

        if (empty($transaction)) {
            Flash::error('Transaction not found');

            return redirect(route('transactions.index'));
        }

        return view('transactions.edit')->with('transaction', $transaction);
    }

    /**
     * Update the specified Transaction in storage.
     *
     * @param  int              $id
     * @param UpdateTransactionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTransactionRequest $request)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $transaction = $this->transactionRepository->findWithoutFail($id);

        if (empty($transaction)) {
            Flash::error('Transaction not found');

            return redirect(route('transactions.index'));
        }

        $transaction = $this->transactionRepository->update($request->all(), $id);

        Flash::success('Transaction updated successfully.');

        return redirect(route('transactions.index'));
    }

    /**
     * Remove the specified Transaction from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $transaction = $this->transactionRepository->findWithoutFail($id);

        if (empty($transaction)) {
            Flash::error('Transaction not found');

            return redirect(route('transactions.index'));
        }

        $this->transactionRepository->delete($id);

        Flash::success('Transaction deleted successfully.');

        return redirect(route('transactions.index'));
    }
}

resources/views/transactions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'transactions.store']) !!}

                        @include('transactions.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/transactions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($transaction, ['route' => ['transactions.update', $transaction->id], 'method' => 'patch']) !!}

                        @include('transactions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/transactions/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Paymenttype Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('paymenttype_id', 'Paymenttype Id:') !!}
    {!! Form::number('paymenttype_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Total Prices Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_prices', 'Total Prices:') !!}
    {!! Form::number('total_prices', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Province Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('province_id', 'Province Id:') !!}
    {!! Form::text('province_id', null, ['class' => 'form-control']) !!}
</div>

<!-- City Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('city_id', 'City Id:') !!}
    {!! Form::text('city_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Neighbourhood Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Neighbourhood_id', 'Neighbourhood Id:') !!}
    {!! Form::text('Neighbourhood_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('transactions.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/transactions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Transactions</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('transactions.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('transactions.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/transactions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('transactions.show_fields')
                    <a href="{!! route('transactions.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>

        </div>

        <div class="box box-primary">
            <table class="table table-responsive" id="allsells-table">
                <thead>
                <tr>
                    <th>Product Id</th>
                    <th>Transaction Id</th>
                    <th>Count</th>
                    <th colspan="3">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($allsells as $allsell)
                    <tr>
                        <td>{!! $allsell->product_id !!}</td>
                        <td>{!! $allsell->transaction_id !!}</td>
                        <td>{!! $allsell->count !!}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{!! route('allsells.show', [$allsell->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div class="box box-primary">
            <table class="table table-responsive" id="shipments-table">
                <thead>
                <tr>
                    <th>Shipmenttype Id</th>
                    <th>Send Date</th>
                    <th>Delivered Date</th>
                    <th colspan="3">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($shipments as $shipment)
                    <tr>
                        <td>{!! $shipment->shipmenttype_id !!}</td>
                        <td>{!! $shipment->send_date !!}</td>
                        <td>{!! $shipment->delivered_date !!}</td>
                        <td>
                            <a href="{!! route('shipments.show', [$shipment->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/transactions/show_fields.blade.php
<!-- Id Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $transaction->id !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{!! $transaction->user_id !!}</p>
</div>

<!-- Paymenttype Id Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('paymenttype_id', 'Paymenttype Id:') !!}
    <p>{!! $transaction->paymenttype_id !!}</p>
</div>

<!-- Total Prices Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('total_prices', 'Total Prices:') !!}
    <p>{!! $transaction->total_prices !!}</p>
</div>

<!-- Status Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('status', 'Status:') !!}
    <p>{!! $transaction->status !!}</p>
</div>

<!-- Province Id Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('province_id', 'Province Id:') !!}
    <p>{!! $transaction->province_id !!}</p>
</div>

<!-- City Id Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('city_id', 'City Id:') !!}
    <p>{!! $transaction->city_id !!}</p>
</div>

<!-- Neighbourhood Id Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('Neighbourhood_id', 'Neighbourhood Id:') !!}
    <p>{!! $transaction->Neighbourhood_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $transaction->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group col-sm-3 col-sm-4">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $transaction->updated_at !!}</p>
</div>

resources/views/transactions/table.blade.php
<table class="table table-responsive" id="transactions-table">
    <thead>
        <tr>
            <th>User Id</th>
        <th>Paymenttype Id</th>
        <th>Total Prices</th>
        <th>Status</th>
        <th>Province Id</th>
        <th>City Id</th>
        <th>Neighbourhood Id</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($transactions as $transaction)
        <tr>
            <td>{!! $transaction->user_id !!}</td>
            <td>{!! $transaction->paymenttype_id !!}</td>
            <td>{!! $transaction->total_prices !!}</td>
            <td>{!! $transaction->status !!}</td>
            <td>{!! $transaction->province_id !!}</td>
            <td>{!! $transaction->city_id !!}</td>
            <td>{!! $transaction->Neighbourhood_id !!}</td>
            <td>
                {!! Form::open(['route' => ['transactions.destroy', $transaction->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('transactions.show', [$transaction->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('transactions.edit', [$transaction->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>