routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

$this->get('admin-panel/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin-panel/login', 'Auth\LoginController@login');
//$this->post('admin-panel/logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
//$this->get('admin-panel/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');


Route::group(['middleware'=>'auth'],function (){

    Route::resource('admin-panel/users', 'AdminPanel\UserController');

    Route::resource('admin-panel/roles', 'AdminPanel\RoleController');

    Route::resource('admin-panel/products', 'AdminPanel\ProductController');

    Route::resource('admin-panel/images', 'AdminPanel\ImageController');

    Route::resource('admin-panel/shipments', 'AdminPanel\ShipmentController');

    Route::resource('admin-panel/postmen', 'AdminPanel\PostmanController');

    Route::resource('admin-panel/transactions', 'AdminPanel\TransactionController');

    Route::resource('admin-panel/allsells', 'AdminPanel\AllsellController');

    Route::resource('admin-panel/comments', 'AdminPanel\CommentController');

    Route::resource('admin-panel/images', 'AdminPanel\ImageController');

    Route::resource('admin-panel/shipmentTypes', 'AdminPanel\ShipmentTypeController');

    Route::resource('admin-panel/paymentTypes', 'AdminPanel\PaymentTypeController');

    Route::resource('admin-panel/productTypes', 'AdminPanel\ProductTypeController');

    Route::resource('admin-panel/posts', 'AdminPanel\PostController');

    Route::get('/admin-panel', 'AdminPanel\AdminPanelController@index');

});

//Route::get('/home', 'HomeController@index');

//API

Route::get('/buyershow/{id}','Front\API\BuyerProductController@show');
Route::get('/buyershowall', 'Front\API\BuyerProductController@showall');
Route::get('/comm/{id}', 'Front\api\BuyerProductController@showcomments');
Route::get('/clientshowpost/{id}', 'Front\API\ClientPostController@show');
Route::get('/clientshowallpost', 'Front\API\ClientPostController@showall');

Route::get('/cartdtail', 'Front\API\CartDtailController@showall');


Route::get('login', 'Front\LoginController@index');

//Route::get('register', 'Front\RegisterController@index');

Route::get('/', 'Front\HomeController@index');

Route::get('address', 'Front\AddressController@index');

Route::get('reviewaddress', 'Front\ReviewAddressController@index');

Route::get('calculations', 'Front\CalculationsController@index');

Route::get('cart', 'Front\Cart1Controller@index');

Route::get('review', 'Front\ReviewController@index');

Route::get('paymentsuccess', 'Front\PayMentSuccessController@index');

Route::get('product', 'Front\ProductController@index');

Route::get('product/{id}', 'Front\ProductController@index');

Route::get('profile', 'Front\ProfileController@index');

Route::get('blog', 'Front\BlogController@index');

//Route::get('blog/post', 'Front\PostController@index');
Route::get('blog/post/{id}', 'Front\PostController@show');

Route::get('finalstep', 'Front\FinalStepController@index');

//summernote store route
Route::post('/summernote','SummernoteController@store')->name('summernotePersist');

//summernote display route
Route::get('/summernote_display','SummernoteController@show')->name('summernoteDispay');

Route::resource('posts', 'PostController');

Route::resource('postTags', 'PostTagController');





//
Route::get('/profile/profile',function(){
    return view('front.Profile.profile');
});
Route::get('/profile/information',function(){
    return view('front.Profile.information');
});
Route::get('/profile/address',function(){
    return view('front.Profile.address');
});
Route::get('/profile/bookmark',function(){
    return view('front.Profile.bookmark');
});
Route::get('/profile/changeAvatar',function(){
    return view('front.Profile.changeAvatar');
});
Route::get('/profile/changePassword',function(){
    return view('front.Profile.changePassword');
});
Route::get('/profile/order',function(){
    return view('front.Profile.order');
});
Route::get('/profile/question',function(){
    return view('front.Profile.question');
});
Route::get('/profile/requestreturn',function(){
    return view('front.Profile.requestreturn');
});

app/Http/Controllers/AdminPanel/PaymentTypeController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Http\Requests\CreatePaymentTypeRequest;
use App\Http\Requests\UpdatePaymentTypeRequest;
use App\Repositories\PaymentTypeRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Http\Controllers\AdminPanel\CheckRoleAdmin;

class PaymentTypeController extends AppBaseController
{
    /** @var  PaymentTypeRepository */
    private $paymentTypeRepository;

    public function __construct(PaymentTypeRepository $paymentTypeRepo)
    {
        $this->paymentTypeRepository = $paymentTypeRepo;
    }

    /**
     * Display a listing of the PaymentType.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $this->paymentTypeRepository->pushCriteria(new RequestCriteria($request));
        $paymentTypes = $this->paymentTypeRepository->all();

        return view('payment_types.index')
            ->with('paymentTypes', $paymentTypes);
    }

    /**
     * Show the form for creating a new PaymentType.
     *
     * @return Response
     */
    public function create()
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        return view('payment_types.create');
    }

    /**
     * Store a newly created PaymentType in storage.
     *
     * @param CreatePaymentTypeRequest $request
     *
     * @return Response
     */
    public function store(CreatePaymentTypeRequest $request)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $input = $request->all();

        $paymentType = $this->paymentTypeRepository->create($input);

        Flash::success('Payment Type saved successfully.');

        return redirect(route('paymentTypes.index'));
    }

    /**
     * Display the specified PaymentType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $paymentType = $this->paymentTypeRepository->findWithoutFail($id);

        if (empty($paymentType)) {
            Flash::error('Payment Type not found');

            return redirect(route('paymentTypes.index'));
        }

        return view('payment_types.show')->with('paymentType', $paymentType);
    }

    /**
     * Show the form for editing the specified PaymentType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $paymentType = $this->paymentTypeRepository->findWithoutFail($id);

        if (empty($paymentType)) {
            Flash::error('Payment Type not found');

            return redirect(route('paymentTypes.index'));
        }

        return view('payment_types.edit')->with('paymentType', $paymentType);
    }

    /**
     * Update the specified PaymentType in storage.
     *
     * @param  int              $id
     * @param UpdatePaymentTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePaymentTypeRequest $request)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $paymentType = $this->paymentTypeRepository->findWithoutFail($id);

        if (empty($paymentType)) {
            Flash::error('Payment Type not found');

            return redirect(route('paymentTypes.index'));
        }

        $paymentType = $this->paymentTypeRepository->update($request->all(), $id);

        Flash::success('Payment Type updated successfully.');

        return redirect(route('paymentTypes.index'));
    }

    /**
     * Remove the specified PaymentType from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        if(!CheckRoleAdmin::CheckRoleAdmin(auth()->user()->role_id)) {

            return view('404');

        }

        $paymentType = $this->paymentTypeRepository->findWithoutFail($id);

        if (empty($paymentType)) {
            Flash::error('Payment Type not found');

            return redirect(route('paymentTypes.index'));
        }

        $this->paymentTypeRepository->delete($id);

        Flash::success('Payment Type deleted successfully.');

        return redirect(route('paymentTypes.index'));
    }
}

resources/views/payment_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Payment Type
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'paymentTypes.store']) !!}

                        @include('payment_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/payment_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Payment Type
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($paymentType, ['route' => ['paymentTypes.update', $paymentType->id], 'method' => 'patch']) !!}

                        @include('payment_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/payment_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('paymentTypes.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/payment_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Payment Types</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('paymentTypes.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('payment_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/payment_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Payment Type
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('payment_types.show_fields')
                    <a href="{!! route('paymentTypes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/payment_types/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $paymentType->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $paymentType->name !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $paymentType->deleted_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $paymentType->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $paymentType->updated_at !!}</p>
</div>

resources/views/payment_types/table.blade.php
<table class="table table-responsive" id="paymentTypes-table">
    <thead>
        <tr>
            <th>Name</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($paymentTypes as $paymentType)
        <tr>
            <td>{!! $paymentType->name !!}</td>
            <td>
                {!! Form::open(['route' => ['paymentTypes.destroy', $paymentType->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('paymentTypes.show', [$paymentType->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('paymentTypes.edit', [$paymentType->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>